사용자는 자신의 도서 대출이력을 조회할 수 있어야 한다
okbut/corporate-library-api pull request #14
Opened 2021-11-28 13:47 UTC by chxxsa

2021-11-29 10:40 UTC, markruler requested changes

2021-11-29 10:40 UTC, markruler commented on apiserver/src/main/java/com/okbut/api/checkout/controller/CheckoutController.java
> +@RequestMapping("/checkout")
이렇게 매핑되면 `/checkout/users/{id}` 형태가 될 텐데 URI는 계층 구조를 표현하는 게 이해하기 좋다고 생각합니다. 예를 들어 사용자의 대출 이력 정보를 조회한다면 `GET /users/{id}/checkouts`가 될 수 있지만 새로 대출하는 경우라면 `POST /books/{id}/checkout`과 같은 형태가 될 수 있을 것 같아요.

[관련 글](https://meetup.toast.com/posts/92) 읽어보시고 의견 남겨주세요.

2021-11-29 10:40 UTC, markruler commented on apiserver/src/main/java/com/okbut/api/checkout/domain/Checkout.java
> +public class Checkout {
테이블명은 Check와 Out이 나뉘는데 클래스명은 한 단어로 보입니다.

```suggestion
@Table(name="CHECK_OUT")
public class CheckOut {
```

2021-11-29 10:40 UTC, markruler commented on apiserver/src/main/java/com/okbut/api/checkout/domain/Checkout.java
> +    private Long bookId;
빈 줄을 둬서 가독성을 올리는 건 어떨까요?

```suggestion
    @Id
    @GeneratedValue
    @Column(nullable = false)
    private Long id;

    @CreatedDate
    @Column(name="CHECKOUT_DTM", nullable = false)
    private LocalDateTime checkoutDtm;

    @Column(name="RETURN_DTM", nullable = false)
    private LocalDateTime returnDtm;

    @Column(name="IS_RENEWED", nullable = false)
    private boolean isRenewed;

    @ManyToOne
    @JoinColumn(name="USER_ID")
    @Column(nullable = false)
    private Long userId;

    @ManyToOne
    @JoinColumn(name="BOOK_ID")
    @Column(nullable = false)
    private Long bookId;
```

2021-11-29 10:40 UTC, markruler commented on apiserver/src/test/java/com/okbut/api/checkout/application/CheckoutServiceTest.java
> +                final List<Checkout> checkoutList = checkoutService.findCheckoutHistoryOfUser(validUserId);
Service에서 어떤 값이 리턴되길 기대하는지 `given()`이 필요할 것 같아요

2021-11-29 10:40 UTC, markruler commented on apiserver/src/test/java/com/okbut/api/checkout/application/CheckoutServiceTest.java
> +}
개행 문자를 넣어주세요

2021-11-29 10:40 UTC, markruler commented on apiserver/src/test/java/com/okbut/api/checkout/application/CheckoutServiceTest.java
> +}
[관련 글](https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/)

2021-11-29 11:27 UTC, markruler requested changes
Controller 테스트를 작성하고 Spring REST Docs로 문서가 생성되도록 만들어주세요.

2021-11-29 14:20 UTC, chxxsa commented on apiserver/src/main/java/com/okbut/api/checkout/domain/Checkout.java
> +public class Checkout {
통일성을 위해서 전부 소문자로 한건데,, entity만 일단 바꿀게요

2021-11-29 16:06 UTC, chxxsa commented on apiserver/src/main/java/com/okbut/api/checkout/controller/CheckoutController.java
> +@RequestMapping("/checkout")
계층구조를 생각 못했네요.  책의 경우에도 /checkout/books/{id} 이런식으로 생각했는데 계층구조 생각하면 말씀하신대로 소유? 측면에서 checkout 이 젤 우측으로 오는게 맞는거 같습니다.

2021-11-29 16:06 UTC, chxxsa commented on apiserver/src/main/java/com/okbut/api/checkout/domain/Checkout.java
> +    private Long bookId;
ㅋㅋㅋ수정했습니다

2021-12-19 10:25 UTC, chxxsa commented
![image](https://user-images.githubusercontent.com/19724782/146671686-ab627854-b71c-4461-b0ed-ce059cfabd52.png)

2021-12-29 14:58 UTC, markruler commented
고생하셨습니다! 🤗️

2021-12-29 14:58 UTC, markruler approved these changes

2021-12-29 14:59 UTC, merged