관리자는 도서를 등록할 수 있어야 한다.
okbut/corporate-library-api pull request #15
Opened 2021-11-29 15:04 UTC by moonorbit

2021-12-03 14:41 UTC, markruler requested changes

2021-12-03 14:41 UTC, markruler commented on apiserver/src/test/java/com/okbut/api/books/controller/BookControllerTest.java
> +                    .andExpect(jsonPath("$.[?(@.isbn == '%d')]", isbn).exists())
이렇게 변경하는 것이 더 읽기 쉽지 않을까요?

```suggestion
                    .andExpect(jsonPath("$.isbn", equalTo(isbn)))
```

2021-12-03 14:41 UTC, markruler commented on apiserver/src/test/java/com/okbut/api/books/controller/BookControllerTest.java
> +                        .regDtm(LocalDateTime.now()).build();
빌더 형태의 경우 아래와 같이 wrapping 해주는 것이 더 읽기 좋을 것 같아요.

```suggestion
        final Book book =
                Book.builder()
                        .isbn(isbn)
                        .name("도서명")
                        .publisher("출판사")
                        .author("테드창")
                        .editor("편집자")
                        .language("ko")
                        .publicationDtm(LocalDateTime.now())
                        .regDtm(LocalDateTime.now())
                        .build();
```

2021-12-03 14:41 UTC, markruler commented on apiserver/src/test/java/com/okbut/api/books/controller/BookControllerTest.java
> +            given(bookService.registerBook(any(Book.class))).willReturn(book);
POST API로 생성한 객체를 다시 반환해야 할 이유는 무엇인가요?

2021-12-03 14:41 UTC, markruler commented on apiserver/src/test/java/com/okbut/api/books/controller/BookControllerTest.java
> +        // TODO : 만약 관리자 권한을 가진 아이디가 주어진다면 (관리자 권한은 뭘로 판별하지..)
주석은 개인을 위한 것이 아닌 타인을 위한 것이라고 생각합니다.
지금은 스터디 동료를 위해 작성해주세요.

2021-12-03 14:41 UTC, markruler commented on apiserver/src/test/java/com/okbut/api/books/controller/BookControllerTest.java
> +                    .content(objectMapper.writeValueAsString(book));
Java Bean Mapping을 활용하신다면 Controller 소스에서도 `@Entity` 아닌 DTO로 입력받아 `@Entity`로 변환해서 전달해보시겠어요? 저희가 사용하고 있는 SonarLint 플러그인에서도 해당 힌트를 보여주고 있습니다. [SonarSource - java:S4684](https://rules.sonarsource.com/java/tag/spring/RSPEC-4684)

![image](https://user-images.githubusercontent.com/38225900/144620374-bd48f987-c282-4d4a-9b35-4a271f9a6260.png)

2021-12-03 14:41 UTC, markruler commented on apiserver/src/test/java/com/okbut/api/books/controller/BookControllerTest.java
> +@AutoConfigureRestDocs
Rest Docs를 위한 어노테이션은 있지만 API 문서화를 위한 코드는 추가하지 않으셨네요.
협업을 위해 문서를 작성해주세요.

2021-12-03 14:42 UTC, markruler commented
`Service` 테스트 코드도 작성해주세요.

2021-12-06 15:25 UTC, moonorbit commented on apiserver/src/test/java/com/okbut/api/books/controller/BookControllerTest.java
> +        // TODO : 만약 관리자 권한을 가진 아이디가 주어진다면 (관리자 권한은 뭘로 판별하지..)
음 .. 저때 당시에 PR로 질문을 어떻게 남길까 하다가 TODO 작성하면서 독백처럼 남긴거 같아요.
수정하겠습니다 :)

2022-01-28 06:37 UTC, markruler approved these changes

2022-01-28 06:38 UTC, merged